import Head from 'next/head'

const MAPPING = {
  A: () => <h1>A</h1>,
  B: () => <h1>B</h1>,
  C: () => <h1>C</h1>
};

const ComponentWithMapping = ({ value }) => {
  if (!value) {
    return null;
  }

  const COMPONENT_WITH_MAPPING = MAPPING[value];

  return <COMPONENT_WITH_MAPPING />;
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ComponentWithMapping value="D"/>
      </main>
    </div>
  )
}
